// <auto-generated />
namespace FriendlyHelpers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changes1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changes1));
        
        string IMigrationMetadata.Id
        {
            get { return "201608200027398_Changes1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
